const NAMESPACE_MUI = 'REACT_DASHBOARD_MUI_';

const actions = {
  UPDATED_FORM: `${NAMESPACE_MUI}UPDATED_FORM`,
  
  REGISTER_NEW_USER: `${NAMESPACE_MUI}REGISTER_NEW_USER`,
  REGISTER_NEW_USER_SUCCESSFUL: `${NAMESPACE_MUI}REGISTER_NEW_USER_SUCCESSFUL`,
  REGISTER_NEW_USER_FAILED: `${NAMESPACE_MUI}REGISTER_NEW_USER_FAILED`,
  
  RECOVER_USER_PASSWORD: `${NAMESPACE_MUI}RECOVER_USER_PASSWORD`,
  RECOVER_USER_PASSWORD_SUCCESSFUL: `${NAMESPACE_MUI}RECOVER_USER_PASSWORD_SUCCESSFUL`,
  RECOVER_USER_PASSWORD_FAILED: `${NAMESPACE_MUI}RECOVER_USER_PASSWORD_FAILED`,
  
  LOGIN_USER: `${NAMESPACE_MUI}LOGIN_USER`,
  LOGIN_USER_SUCCESSFUL: `${NAMESPACE_MUI}LOGIN_USER_SUCCESSFUL`,
  LOGIN_USER_FAILED: `${NAMESPACE_MUI}LOGIN_USER_FAILED`,
  LOGOUT_USER: `${NAMESPACE_MUI}LOGOUT_USER`,
  
  FETCH_TODAY_ACTIVITIES: `${NAMESPACE_MUI}FETCH_TODAY_ACTIVITIES`,
  FETCH_OFFLINE_ACTIVITIES: `${NAMESPACE_MUI}FETCH_OFFLINE_ACTIVITIES`,
  FETCH_ONLINE_ACTIVITIES: `${NAMESPACE_MUI}FETCH_ONLINE_ACTIVITIES`,
  CREATE_ACTIVITY: `${NAMESPACE_MUI}CREATE_ACTIVITY`,
  REMOVE_ACTIVITY: `${NAMESPACE_MUI}REMOVE_ACTIVITY`,
  UPDATE_ACTIVITY: `${NAMESPACE_MUI}UPDATE_ACTIVITY`,
  START_EDIT_ACTIVITY: `${NAMESPACE_MUI}START_EDIT_ACTIVITY`,
  SAVE_EDIT_ACTIVITY: `${NAMESPACE_MUI}SAVE_EDIT_ACTIVITY`,
  CANCEL_EDIT_ACTIVITY: `${NAMESPACE_MUI}CANCEL_EDIT_ACTIVITY`,
  UPDATED_ACTIVITY_FORM: `${NAMESPACE_MUI}UPDATED_ACTIVITY_FORM`,

  FETCH_KINDS: `${NAMESPACE_MUI}FETCH_KINDS`,
  FETCH_KINDS_SUCCESSFUL: `${NAMESPACE_MUI}FETCH_KINDS_SUCCESSFUL`,
};

export { actions as default };
